export const productData = [
  {
    id: 1,
    title: "Adicolor Classics Joggers",
    category: "Dress",
    price: 63.85,
    image: "/img/images/products/image1.png",
    status: "Best Selers",
  },
  {
    id: 2,
    title: "Nike Sportswear Futura Luxe",
    category: "Bag",
    price: 130.0,
    image: "/img/images/products/image2.png",
    status: "Best Selers",
  },
  {
    id: 3,
    title: "Geometric print Scarf",
    category: "Dress",
    price: 53.0,
    image: "/img/images/products/image3.png",
    status: "Best Selers",
  },
  {
    id: 4,
    title: "Yellow Reserved Hoodie",
    category: "Hoodies",
    price: 63.85,
    image: "/img/images/products/image4.png",
    status: "New Arriaval",
  },
  {
    id: 5,
    title: "Basic Dress Green",
    category: "Dress",
    price: 236.0,
    image: "/img/images/products/image5.png",
    status: "New Arriaval",
  },
  {
    id: 6,
    title: "Nike Air Zoom Pegasus",
    category: "Shoe",
    price: 198.0,
    image: "/img/images/products/image6.png",
    status: "Best Selers",
  },
  {
    id: 7,
    title: "Nike Repel Miler",
    category: "Hoodies",
    price: 120.5,
    image: "/img/images/products/image7.png",
    status: "Best Selers",
  },
  {
    id: 8,
    title: "Nike Sportswear Futura Luxe",
    category: "Glasses",
    price: 160.0,
    image: "/img/images/products/image8.png",
  },
  {
    id: 9,
    title: "Adicolor Classics Joggers",
    category: "Dress",
    price: 63.85,
    image: "/img/images/products/image1.png",
    status: "Best Selers",
  },
  {
    id: 10,
    title: "Nike Sportswear Futura Luxe",
    category: "Bag",
    price: 130.0,
    image: "/img/images/products/image2.png",
    status: "Best Selers",
  },
  {
    id: 11,
    title: "Geometric print Scarf",
    category: "Dress",
    price: 53.0,
    image: "/img/images/products/image3.png",
    status: "Best Selers",
  },
  {
    id: 12,
    title: "Yellow Reserved Hoodie",
    category: "Hoodies",
    price: 63.85,
    image: "/img/images/products/image4.png",
    status: "New Arriaval",
  },
  {
    id: 13,
    title: "Basic Dress Green",
    category: "Dress",
    price: 236.0,
    image: "/img/images/products/image5.png",
    status: "New Arriaval",
  },
  {
    id: 14,
    title: "Nike Air Zoom Pegasus",
    category: "Shoe",
    price: 198.0,
    image: "/img/images/products/image6.png",
    status: "Best Selers",
  },
  {
    id: 15,
    title: "Nike Repel Miler",
    category: "Hoodies",
    price: 120.5,
    image: "/img/images/products/image7.png",
    status: "Best Selers",
  },
  {
    id: 16,
    title: "Nike Sportswear Futura Luxe",
    category: "Glasses",
    price: 160.0,
    image: "/img/images/products/image8.png",
  },
];
